
import { GoogleGenAI, Modality } from "@google/genai";

// Ensure the API key is available in the environment variables
const API_KEY = process.env.API_KEY;
if (!API_KEY) {
  throw new Error("API_KEY environment variable not set.");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

export async function runAgent<T,>(prompt: string): Promise<T> {
  try {
    const response = await ai.models.generateContent({
        model: 'gemini-2.5-pro',
        contents: prompt,
        config: {
            responseMimeType: 'application/json',
        }
    });

    const text = response.text.trim();
    
    // Sometimes the API might wrap the JSON in ```json ... ```, so we strip it.
    const jsonText = text.replace(/^```json\n?/, '').replace(/```$/, '');

    return JSON.parse(jsonText) as T;
  } catch (error) {
    console.error("Error calling Gemini API:", error);
    if (error instanceof SyntaxError) {
        throw new Error("Failed to parse the AI's response. The model did not return valid JSON.");
    }
    throw new Error(`An error occurred while communicating with the AI. Details: ${error.message}`);
  }
}

export async function generateImage(prompt: string): Promise<string> {
    try {
        const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash-image',
            contents: {
                parts: [{ text: prompt }],
            },
            config: {
                responseModalities: [Modality.IMAGE],
            },
        });

        for (const part of response.candidates[0].content.parts) {
            if (part.inlineData) {
                const base64ImageBytes: string = part.inlineData.data;
                return `data:image/png;base64,${base64ImageBytes}`;
            }
        }
        
        throw new Error("No image was generated by the model.");

    } catch (error) {
        console.error("Error calling Gemini Image API:", error);
        throw new Error(`An error occurred while generating the image. Details: ${error.message}`);
    }
}
